GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Kyle",
    "number": "11-22"
}
###
DELETE http://localhost:3001/api/persons/63f601ad06a84338d65e8855